import {Composition} from 'remotion';
import {H, T, W} from './brand';
import {QashatiLayers} from './QashatiLayers';

// Qashati Alsham — first social spot. Music is generated by audio/make_score.py.
export const QashatiCompositions: React.FC = () => (
  <Composition
    id="QashatiLayers"
    component={QashatiLayers}
    durationInFrames={T.end}
    fps={30}
    width={W}
    height={H}
    defaultProps={{music: 'qashati/audio/layers.mp3'}}
  />
);
