"""Split the traced Qashati logo (logo.svg) into animatable groups -> video/src/qashati/logoPaths.ts.
Usage (repo root): python3 brands/qashati-alsham/logo_to_ts.py
"""
import json
import os
import re

from svgpathtools import parse_path

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', '..', 'video', 'src', 'qashati', 'logoPaths.ts')

svg = open(os.path.join(HERE, 'logo.svg')).read()
_, _, W, H = (float(v) for v in re.search(r'viewBox="([^"]+)"', svg).group(1).split())
transform = re.search(r'<g[^>]*transform="([^"]+)"', svg).group(1)
ty = float(re.search(r'translate\(([-\d.]+),([-\d.]+)\)', transform).group(2))
sx, sy = (float(v) for v in re.search(r'scale\(([-\d.]+),([-\d.]+)\)', transform).groups())


def fmt(d):
    return re.sub(r'-?\d+\.\d+', lambda m: f'{float(m.group()):.1f}'.rstrip('0').rstrip('.'), d)


groups = {'dots': [], 'q': [], 'arabic': [], 'latin': []}
for d in re.findall(r'<path[^>]*\sd="([^"]+)"', svg):
    p = parse_path(d).scaled(sx, sy).translated(complex(0, ty))  # potrace units -> viewBox units
    x0, x1, y0, y1 = p.bbox()
    key = 'dots' if y1 < 0.16 * H else 'q' if y0 < 0.2 * H and y1 > 0.5 * H else 'latin' if y0 > 0.935 * H else 'arabic'
    groups[key].append((x0, fmt(p.d())))

# Dots left -> right; Arabic right -> left (reading order); Latin left -> right.
groups['dots'].sort()
groups['latin'].sort()
groups['arabic'].sort(reverse=True)

with open(OUT, 'w') as f:
    f.write('// Generated by brands/qashati-alsham/logo_to_ts.py from logo.svg — regenerate, do not edit.\n')
    f.write('export const qashatiLogo = {\n')
    f.write(f'  width: {W:g},\n  height: {H:g},\n')
    for k, v in groups.items():
        f.write(f'  {k}: {json.dumps([d for _, d in v])},\n')
    f.write('};\n')
print({k: len(v) for k, v in groups.items()}, '->', os.path.relpath(OUT))
