#!/usr/bin/env python3
"""Shape the spot's hero type with HarfBuzz (Lalezar) and export the glyph outlines as SVG paths → parts/glyphs.ts.

Why vectors and not HTML text: the gag needs the ق of «قشطة» as its own object (flicked away, boomerangs back) while
the rest of the word stays a correctly JOINED Arabic word, the ق's font dots replaced by the brand's two cream drops,
and the ش re-shaped medial → initial when the ق is gone («شطة» heals). HarfBuzz gives the real contextual forms and
positions, so the joins stay exactly as the font draws them (nothing is animated letter by letter).

Run from video/:  python3 src/qashati2d/qaf/tools/make_glyphs.py
"""
import json
from pathlib import Path

import uharfbuzz as hb
from fontTools.pens.recordingPen import DecomposingRecordingPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

HERE = Path(__file__).resolve().parent
VIDEO = HERE.parents[3]
FONT = VIDEO / "public/qashati2/fonts/Lalezar-400.ttf"
OUT = HERE.parent / "parts/glyphs.ts"

RUNS = {
    "qashta": "قشطة",
    "shatta": "شطة",
    "title1": "الفرق كلّو",
    "title2": "بحرف.",
    "title3": "بالـ ق.",
}
# qaf glyphs whose dots are swapped for the logo's drops: contours whose yMin is above this are "dots"
QAF_GLYPHS = {"uniFED7": 420, "uni0642": 440}

tt = TTFont(str(FONT))
gs = tt.getGlyphSet()
upm = tt["head"].unitsPerEm
blob = hb.Blob.from_file_path(str(FONT))
face = hb.Face(blob)
font = hb.Font(face)


def contours(name):
    rp = DecomposingRecordingPen(gs)
    gs[name].draw(rp)
    out, cur = [], []
    for op, args in rp.value:
        cur.append((op, args))
        if op in ("closePath", "endPath"):
            out.append(cur)
            cur = []
    return out


def to_d(conts):
    pen = SVGPathPen(gs)
    for c in conts:
        for op, args in c:
            getattr(pen, op)(*args)
    return pen.getCommands()


def bbox(conts):
    pts = [p for c in conts for _, a in c for p in a]
    if not pts:
        return [0, 0, 0, 0]
    xs = [p[0] for p in pts]
    ys = [p[1] for p in pts]
    # SVG space: y down (flip)
    return [min(xs), -max(ys), max(xs), -min(ys)]


glyphs = {}
runs = {}
for key, text in RUNS.items():
    buf = hb.Buffer()
    buf.add_str(text)
    buf.guess_segment_properties()
    hb.shape(font, buf, {})
    # word index per cluster (cluster = UTF-32 index into text)
    word_of = []
    w = 0
    for ch in text:
        if ch == " ":
            word_of.append(-1)
            w += 1
        else:
            word_of.append(w)
    x = 0
    items = []
    for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
        name = font.glyph_to_string(info.codepoint)
        if name != "space":
            items.append({"g": name, "x": x + pos.x_offset, "y": -pos.y_offset, "w": word_of[info.cluster], "cl": info.cluster})
            if name not in glyphs:
                cs = contours(name)
                g = {"adv": gs[name].width, "d": to_d(cs), "bbox": bbox(cs)}
                if name in QAF_GLYPHS:
                    lim = QAF_GLYPHS[name]
                    body = [c for c in cs if min(p[1] for _, a in c for p in a) < lim]
                    dots = [c for c in cs if min(p[1] for _, a in c for p in a) >= lim]
                    g["body"] = to_d(body)
                    g["dots"] = to_d(dots)
                    g["dotsBox"] = bbox(dots)
                glyphs[name] = g
        x += pos.x_advance
    runs[key] = {"text": text, "width": x, "glyphs": items}

ts = [
    "// Generated by qaf/tools/make_glyphs.py (HarfBuzz-shaped Lalezar outlines) — regenerate, do not edit.",
    "// Font units (UPM %d), SVG orientation (y down), baseline y = 0; run glyphs are in VISUAL order (left → right)." % upm,
    "export type GlyphDef = {adv: number; d: string; bbox: [number, number, number, number]; body?: string; dots?: string; dotsBox?: [number, number, number, number]};",
    "export type RunGlyph = {g: string; x: number; y: number; w: number; cl: number};",
    "export type Run = {text: string; width: number; glyphs: RunGlyph[]};",
    "export const UPM = %d;" % upm,
    "export const GLYPHS: Record<string, GlyphDef> = %s;" % json.dumps(glyphs, ensure_ascii=False),
    "export const RUNS: Record<%s, Run> = %s;" % (" | ".join(json.dumps(k) for k in RUNS), json.dumps(runs, ensure_ascii=False)),
    "",
]
OUT.write_text("\n".join(ts))
for k, r in runs.items():
    print(k, r["width"], [(g["g"], g["x"], g["w"]) for g in r["glyphs"]])
print("→", OUT)
